version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - nvm install 14
            - nvm use 14
            - node -v
            - yarn install
        build:
          commands:
            - nvm install 14
            - nvm use 14
            - node -v
            - yarn run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: packages/frontends/cms
